# Generated by Django 2.2 on 2020-07-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tucao',
            name='ctime',
            field=models.DateTimeField(),
        ),
    ]
