# Generated by Django 2.2 on 2020-07-21 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20200721_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_tucao',
            name='ss',
            field=models.CharField(max_length=123, null=True),
        ),
        migrations.AlterField(
            model_name='db_tucao',
            name='ctime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
