# Generated by Django 2.2 on 2020-07-21 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_auto_20200721_0219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_tucao',
            name='ss',
        ),
    ]
