# Generated by Django 2.2 on 2020-07-21 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_remove_db_tucao_ss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_tucao',
            name='ctime',
            field=models.DateTimeField(null=True),
        ),
    ]
