# Generated by Django 2.2 on 2020-07-21 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_auto_20200721_0220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_tucao',
            name='ctime',
        ),
    ]
