# Generated by Django 2.2 on 2020-08-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_db_apis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_apis',
            name='api_body',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_apis',
            name='api_host',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='db_apis',
            name='body_method',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='db_apis',
            name='des',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='db_apis',
            name='file_key',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_apis',
            name='file_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='db_apis',
            name='public_header',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
