# Generated by Django 2.2 on 2020-10-09 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0013_db_apis_log'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_apis_log',
            name='name',
        ),
    ]
