# Generated by Django 2.2 on 2020-12-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0021_db_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('host', models.TextField(null=True)),
            ],
        ),
    ]
