# Generated by Django 2.2 on 2020-12-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0022_db_project_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True)),
                ('api_method', models.CharField(max_length=10, null=True)),
                ('api_url', models.CharField(max_length=1000, null=True)),
                ('api_header', models.CharField(max_length=1000, null=True)),
                ('api_host', models.CharField(max_length=100, null=True)),
                ('body_method', models.CharField(max_length=20, null=True)),
                ('api_body', models.CharField(max_length=1000, null=True)),
                ('sign', models.CharField(max_length=10, null=True)),
                ('set', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
