# Generated by Django 2.2 on 2021-01-19 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0023_db_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_step',
            name='api_login',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
