# Generated by Django 2.2 on 2021-03-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0025_db_global_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_global_data',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
