# Generated by Django 2.2 on 2021-06-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0029_db_project_encryption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_project',
            old_name='encryption',
            new_name='encyption_input',
        ),
        migrations.AddField(
            model_name='db_project',
            name='encyption_insert',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
