# Generated by Django 2.2 on 2021-07-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0030_auto_20210625_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_step',
            name='sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='db_apis',
            name='sign',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='db_login',
            name='sign',
            field=models.BooleanField(default=False),
        ),
    ]
