# Generated by Django 2.2 on 2021-07-06 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0031_auto_20210706_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_apis',
            name='sign',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='db_login',
            name='sign',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='db_step',
            name='sign',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
