# Generated by Django 2.2 on 2021-08-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0033_auto_20210706_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='cert',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
