# Generated by Django 2.2 on 2021-08-19 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0034_db_project_cert'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_apis',
            name='api_cert',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='db_apis_log',
            name='api_cert',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='db_login',
            name='cert',
            field=models.CharField(default='no', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='db_step',
            name='api_cert',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
