# Generated by Django 2.2 on 2021-11-03 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0036_auto_20210819_1321'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_cases',
            name='concurrent',
            field=models.BooleanField(default=True),
        ),
    ]
